version: 2.1
jobs:
  prepare:
    docker:
      - image: 'circleci/node:lts'
    steps:
      - checkout
      - run: npm ci
      - run: mkdir -p reports/jest
      - persist_to_workspace:
          root: .
          paths:
            - .
  prebuild_checks:
    docker:
      - image: 'circleci/node:lts'
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Check Code Quality
          command: npx eslint ./src
      - run:
          name: Code Style Check
          command: npx prettier --check src
      - run:
          name: Unit Tests
          command: npx jest --ci --coverage
      - store_test_results:
          path: reports
  build_and_deploy:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: echo "$DO_TOKEN" | docker login $DO_REGISTRY --username $DO_TOKEN --password-stdin
      - run: make build
      - run: make deploy
 
workflows:
  version: 2
  build_and_test:
    jobs:
      - prepare
      - prebuild_checks:
          requires:
            - prepare
      - build_and_deploy:
          context:
            - kenhoward-dev
          filters:
            branches:
              only:
                - main
                - develop
          requires:
            - prebuild_checks
