name: Continuous Integration
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npx eslint && npx tsc --noEmit
    - run: npx jest
    - run: npx prettier --write src
    - run: git diff --exit-code || "Diff shows unformatted changes. Run `npx prettier --write src` to fix the issue."
